apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

# Patch the image in the deployment
images:
- name: jmuachifi/sre-challenge-argocd
  newTag: 380ae9cffa6d3f1759bf471f131fe1612bfe153d
