apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
  - name: jmuachifi/sre-challenge-argocd
    newTag: 731dc1a42ae2328754f2cadca12dbd39d1b2619d
